### ISSUE TITLE
Update the .gitignore file

### ISSUE THREAD

**Issue by prakritigoyal19** [IE-NITK/Redemption#2]
Need to update git ignore file to avoid changes due to gradle syncing.

**Comment by rj-since-2000** [comment]
Which files need to be added to .git ignore ?

**Comment by prakritigoyal19** [comment]
Hey,

This issue has already been solved. You could go through the code and maybe open a few of your own issues.

**Comment by rj-since-2000** [comment]
okay then you can close this issue
